### ISSUE TITLE
App immediately crashes when opening

### ISSUE THREAD

**Issue by Baccount** [AudioKit/AudioKitSynthOne#114] opened 2019-10-22 20:39 UTC
Running iOS 13.1.3 on an iPhone XS Max, the latest version of sync one, 1.2.1 , immediately crashes every single time I try to open it, here is the crash log. 
[AudioKitSynthOne-2019-10-22-133726.zip](https://github.com/AudioKit/AudioKitSynthOne/files/3758461/AudioKitSynthOne-2019-10-22-133726.zip)

**Comment by Baccount** [comment] 2019-10-22 20:41
[AudioKitSynthOne-2019-10-22-133726.zip](https://github.com/AudioKit/AudioKitSynthOne/files/3758459/AudioKitSynthOne-2019-10-22-133726.zip)
Crash log

**Comment by analogcode** [comment] 2019-10-22 21:08
Thanks for this! And, I appreciate the crash log. 

We're having trouble replicating. If you completely delete Synth One and re-download, does it still crash for you?

**Comment by Baccount** [comment] 2019-10-22 21:20
After I deleted and reinstalled the app it still immediately crashes when opened. 

@analogcode

**Comment by analogcode** [comment] 2019-10-22 21:32
Thanks for doing that so quickly. Appreciate it!

**Comment by analogcode** [comment] 2019-10-22 21:43
@sieren and I have been trying to figure this out. He has an 11 Max Pro, and we're able to see where it crashes in your log. But, can't replicate. Could it be some sort of accessibility setting on your device we need to account for? For example, zoom, or some other iOS 13.1.3 magic we haven't yet encountered. The line it's crashing on hasn't been modified in 10 months. So, I wonder if it's not an iOS update and not the Synth One update... thinking out loud

**Comment by Baccount** [comment] 2019-10-22 22:50
@analogcode I have an iPhone XS Max

**Comment by dreness** [comment] 2019-10-26 07:28
"Me too" :) Some additional data points:

- On my 11 Pro (512), crashes on launch. Delete and re-install doesn't help, nor does purging the app data via Settings --> General --> Storage
- On my brother's 11 Pro (256), doesn't crash. Also doesn't crash on his 6s. On both phones, he hadn't ever previously installed the app.

I'm now downloading Xcode 10.3 (need Swift 5.0, but not 5.1) to try to see if the crash repros such that I can debug it myself...

**Comment by sieren** [comment] 2019-10-26 08:01
I merged some fixes to the Develop branch last night that would address the crashes.
Did you change any of the accessibility settings on the Pro at some point? Maybe a restart helps in the meantime (with the settings switched off). At least that helped me when diagnosing the crash.

We‘ll publish a fix very very soon.

**Comment by dreness** [comment] 2019-10-26 08:05
@sieren I just built and installed from the 'develop' branch with Xcode 11.1 (11A1027) (with Xcode-select pointing to 11.1, and after having run 'pod update') - no crash! I did turn off all the entitlement stuff cause I didn't want to deal with setting that up unless I have to, so that's what I'll try next. Also I'll roll back to before your crash fixes to see if I can repro and if the crash log looks familiar.

**Comment by sieren** [comment] 2019-10-26 08:07
Surefire way to reproduce is to go to Accessibility and enable Switch Control.
You‘ll run into a constraints crash first, then a bunch of others... all in line with the crash log posted here and the ones we see in MS App Center.

**Comment by sieren** [comment] 2019-10-26 08:07
Background: The way Views get loaded is different, viewDidLoad gets called twice but there was some audio-relevant code in there that expected to be called once over its lifecycle which I‘ve removed from there.

**Comment by dreness** [comment] 2019-10-26 09:44
@sieren good news: still no crash on develop HEAD with entitlement stuff enabled. Then I rolled back by one commit (and disabled ableton to be able to build) - the crash reproduces. I can’t get a crash log because it dies too fast for Xcode to grab ahold of, and it’s not saving reports locally because it has reached the limit of 25... I understand why that limit is there, and that it’s surely apple’s policy and not yours, but do you know a workaround? I have several hundred GBs free, and I think I can spare the write cycles :)

**Comment by sieren** [comment] 2019-10-26 11:09
If you want to catch the crashes you need to set Breakpoints to break on all exceptions in the debugger :)

**Comment by analogcode** [comment] 2019-10-26 20:47
Thanks for your assistance @dreness! 🙏 
I've submitted a new build to the app store.

**Comment by Baccount** [comment] 2019-10-27 22:53
Thank you for your hard work, the app no longer crashes on my end.

**Closed** 2019-10-27 23:25 UTC
